version: '2'
services:
    db:
        image: dwmkerr/dynamodb
        ports:
            - "8000:8000"
    transactions-api:
        image: bank-api:0.0.1-SNAPSHOT
        restart: always
        depends_on:
            - db
        ports:
            - "8080:8080"